spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/guitar_changer_frame
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
    open-in-view: false
  mvc:
    format:
      date: iso
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1031935853939-03o8jn6uf8o2bo0i0kgquh3ls2se6tc6.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile

springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: 1031935853939-03o8jn6uf8o2bo0i0kgquh3ls2se6tc6.apps.googleusercontent.com
      client-secret: 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
      scopes: openid, email, profile